# Generated by Django 2.2 on 2019-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191020_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='comment',
            field=models.TextField(),
        ),
    ]
